error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20

logging:
  level:
    root: DEBUG

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/readinglist
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
